Several basic examples of building arrays, matrices, and indexing

In [1]:
import numpy as np

Appending Lists

In [2]:
#how to use append to build up a list
#start with an empty list
x = []
#lets fill it with prime numbers
for lp in range(1,30):
    prime_flag = 1
    lp2 = 2
    while (lp2 < lp and prime_flag == 1):
        if (lp/lp2 == int(lp/lp2)):
            prime_flag = 0
        lp2 = lp2 + 1
    if (prime_flag == 1):
        #append ads lp to the end of x
        x.append(lp)
        print(len(x))

print(x)

1
2
3
4
5
6
7
8
9
10
11
[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


Stacking Arrays

In [3]:
#Now I cast it as a np.array so I can manipulate it.
x = np.array(x)
#Since x is a numpy array now, .append no longer works
#So instead I have to do hstack
x = np.hstack((x,31))
print(x)
#hstack can also be used to append larger sequences
print(np.hstack((x,[37,41,43])))
#but unlike hstasck, you have to set x equal to if you want it to stick
print(x)

[ 1  2  3  5  7 11 13 17 19 23 29 31]
[ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43]
[ 1  2  3  5  7 11 13 17 19 23 29 31]


In [4]:
#hstack sticks arrays together horizontally
#vstack is the same used for building 2D arrays
y=2*x
z=3*x
M = np.vstack((x,y))
M = np.vstack((M,z))
print(M)

[[ 1  2  3  5  7 11 13 17 19 23 29 31]
 [ 2  4  6 10 14 22 26 34 38 46 58 62]
 [ 3  6  9 15 21 33 39 51 57 69 87 93]]


In [5]:
#one can also define 1D and 2D arrays explicitly
x = np.array([1,2,3,4,5])
M = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(x)
print(M)

[1 2 3 4 5]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Indexing 2D arrays

In [6]:
#Indexing works as before, except with row, column
#print first row
print(M[0,:])
#print first column
print(M[:,0])
#this is incredibly useful when you forget what order you put your indices


[1 2 3]
[ 1  4  7 10 13]


In [7]:

#Some useful functions for understanding the size and shape of a matrix
#total number of elements
print(np.size(M))
#Number of elements along first index
print(np.size(M,0))
#Number of elements along second index
print(np.size(M,1))
#Number of elements in each index
print(M.shape)


15
5
3
(5, 3)


Multi-element Operations

In [8]:
#instead of indexing each element individually,
#one can apply functions to the whole array

#slow way
for lp in range(len(x)):
  print(np.sin(x[lp]))

#fast way
print(np.sin(x))

0.8414709848078965
0.9092974268256817
0.1411200080598672
-0.7568024953079282
-0.9589242746631385
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [9]:
#By default almost numpy functions operate on an element-wise basis,
#this allows for shorter code that is computationally faster
print(x)
print(x+2)
print(10*x+np.sin(x))
#also for 2D arrays
print(M)
print(M**2)

[1 2 3 4 5]
[3 4 5 6 7]
[10.84147098 20.90929743 30.14112001 39.2431975  49.04107573]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]
 [169 196 225]]


In [10]:
#numpy also has functions that obtains one number from all the elements
print(x)
print(np.sum(x))
print(np.mean(x))
print(np.max(x))
print(np.min(x))
print(np.std(x))

[1 2 3 4 5]
15
3.0
5
1
1.4142135623730951


In [11]:
#Those same operation can be used on 2D arrays
#be default it applies an operation to the entire array
print(M)
print(np.mean(M))
#however, you can also apply it to just one index
print(np.mean(M,0))
print(np.mean(M,1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
8.0
[7. 8. 9.]
[ 2.  5.  8. 11. 14.]


Multi-element Inequalities

In [12]:
#you can also apply an inequality statement and output a boolean to those values for which it applies
cx = np.cos(x)
print(cx)
print(cx > 0)
#number of element of cos(x) which are positive
print(np.sum(cx > 0))
#you can also use this boolean numpy array as an index, to pull out those numbers for which it applies
print(cx[(cx > 0)])
#and finally you can apply a specific operation to just those elements
cx[(cx > 0)] = np.nan
print(cx)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ True False False False  True]
2
[0.54030231 0.28366219]
[        nan -0.41614684 -0.9899925  -0.65364362         nan]


NaN: Not a Number

In [13]:
#by the way nan is "not a number" which is used to eliminate elements of an array (rather than zero)
#you can pick them out with isnan
np.isnan(cx)
#most arithmetic operations don't work on nan
print(np.nan + 5)
print(np.nan > 0)
print(np.nan <= 0)
print(np.mean(cx))
#sometimes there are special functions which skip the nansd
print(np.nanmean(cx))


nan
False
False
nan
-0.6865943180037332


Matrices

In [14]:
#Note that a 2D array is not a matrix.
#When I multiply M by itself in a 2D array, I get element-by-element multiplication
#but that is not how you do matrix multiplication!
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M*M)
print(M)
#you can use np.dot to force it to do matrix multiplication
print(np.dot(M,M))
#or you can cast this 2D array as a numpy matrix, which will default to matrix multiplication
M = np.matrix(M)
print(M*M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
#the same rules apply for treating 1D arrays as a vector
v1 = np.array([1,2,3])
v2 = np.array([1,4,7])
print(v1*v2)
#dot product of vectors defaults to the 1x1 'inner product' not the nxn 'outer product'
print(np.dot(v1,v2))
print(np.dot(v2,v1))
#1D arrays have no sense of orientation
print(v1)
print(v1.T)
#however numpy will treat 1D arrays as a vector if we cast them as a matrix
#what is a vector but a matrix with a dimension of 1xn
v1 = np.matrix(v1)
v2 = np.matrix(v2)
print(v2)
print(v2.T)
print(v1*(v2.T))
print((v1.T)*v2)
print(M*(v1.T))


[ 1  8 21]
30
30
[1 2 3]
[1 2 3]
[[1 4 7]]
[[1]
 [4]
 [7]]
[[30]]
[[ 1  4  7]
 [ 2  8 14]
 [ 3 12 21]]
[[14]
 [32]
 [50]]
